import React, {
  createContext,
  useContext,
  useEffect,
  useMemo,
  useState,
} from 'react';

export type Language = 'vi' | 'en';

const STORAGE_KEY = 'library74.language';

const translations = {
  vi: {
    'brand.name': 'Library74',
    'brand.tagline': 'NEXT-GEN DISCOVERY',
    'common.loading': 'Đang tải...',
    'common.cancel': 'Hủy',
    'common.saveChanges': 'Lưu thay đổi',
    'common.saving': 'Đang lưu...',
    'common.search': 'Tìm kiếm',
    'common.searchBooks': 'Tìm kiếm sách...',
    'common.viewAll': 'Xem tất cả',
    'common.viewDetails': 'Xem chi tiết',
    'common.learnMore': 'Tìm hiểu thêm',
    'common.books': 'sách',
    'common.book': 'Sách',
    'common.or': 'hoặc',
    'common.availableCopies': 'bản khả dụng',
    'common.copies': 'bản',
    'common.logout': 'Đăng xuất',
    'common.dashboard': 'Tổng quan',
    'common.previous': 'Trước',
    'common.next': 'Sau',
    'common.back': 'Quay lại',
    'common.language': 'Ngôn ngữ',
    'common.vietnamese': 'Tiếng Việt',
    'common.english': 'English',

    'nav.home': 'Trang chủ',
    'nav.search': 'Tìm kiếm',
    'nav.categories': 'Danh mục',
    'nav.about': 'Giới thiệu',
    'nav.contact': 'Liên hệ',
    'nav.login': 'Đăng nhập',
    'nav.register': 'Đăng ký',
    'nav.enterDashboard': 'Vào Dashboard',

    'footer.description':
      'Nền tảng thư viện thông minh thế hệ mới nâng tầm khả năng khám phá học thuật và tiếp cận tri thức cho người đọc.',
    'footer.discover': 'Khám phá',
    'footer.support': 'Hỗ trợ',
    'footer.contact': 'Liên hệ',
    'footer.newBooks': 'Sách mới',
    'footer.popularBooks': 'Mượn nhiều nhất',
    'footer.guide': 'Hướng dẫn sử dụng',
    'footer.faq': 'Câu hỏi thường gặp',
    'footer.terms': 'Điều khoản sử dụng',
    'footer.privacy': 'Chính sách bảo mật',
    'footer.serviceTerms': 'Điều khoản dịch vụ',
    'footer.cookie': 'Chính sách Cookie',
    'footer.address':
      'Trường Đại học Bách khoa - ĐHQG TP.HCM\n268 Lý Thường Kiệt, Phường 14, Quận 10, TPHCM',

    'user.section.overview': 'Tổng quan',
    'user.section.personal': 'Quản lý cá nhân',
    'user.section.settings': 'Cài đặt',
    'user.borrowedBooks': 'Sách đang mượn',
    'user.reservations': 'Đặt trước',
    'user.wishlist': 'Yêu thích',
    'user.fines': 'Phí phạt',
    'user.contactSupport': 'Liên hệ & hỗ trợ',
    'user.profile': 'Thông tin cá nhân',
    'user.settings': 'Cài đặt',

    'librarian.librarianPages': 'Librarian Portal',
    'librarian.mainMenu': 'Menu chính',
    'librarian.system': 'Hệ thống',
    'librarian.home': 'Tổng quan',
    'librarian.circulation': 'Quản lý mượn - trả sách',
    'librarian.books': 'Đầu sách',
    'librarian.transactions': 'Lịch sử giao dịch',
    'librarian.copies': 'Bản sao',
    'librarian.contactInbox': 'Hộp thư liên hệ',
    'librarian.reports': 'Báo cáo điều hành',
    'librarian.publicView': 'Giao diện công khai',
    'librarian.settings': 'Cài đặt',
    'librarian.role': 'Thủ thư',
    'librarian.portalName': 'Thủ thư',

    'settings.title': 'Cài đặt',
    'settings.subtitle': 'Tùy chỉnh giao diện và bảo mật tài khoản của bạn.',
    'settings.interface': 'Giao diện',
    'settings.theme': 'Chủ đề',
    'settings.light': 'Sáng',
    'settings.dark': 'Tối',
    'settings.system': 'Theo hệ thống',
    'settings.security': 'Bảo mật',
    'settings.changePassword': 'Đổi mật khẩu',
    'settings.currentPassword': 'Mật khẩu hiện tại',
    'settings.newPassword': 'Mật khẩu mới',
    'settings.confirmPassword': 'Xác nhận mật khẩu mới',
    'settings.passwordHint':
      'Mật khẩu phải có ít nhất 8 ký tự, bao gồm chữ hoa, chữ thường và số',
    'settings.fillPassword': 'Vui lòng nhập đầy đủ thông tin đổi mật khẩu.',
    'settings.passwordLength': 'Mật khẩu mới phải có ít nhất 8 ký tự.',
    'settings.passwordMismatch': 'Mật khẩu xác nhận không khớp.',
    'settings.saved': 'Đã lưu cài đặt.',
    'settings.saveFailed': 'Không thể lưu cài đặt.',

    'common.close': 'Đóng',
    'common.none': 'Không có',
    'common.systemError': 'Lỗi hệ thống',
    'common.showing': 'Hiển thị',
    'common.in': 'trong',
    'dialog.confirmTitle': 'Xác nhận thao tác',
    'dialog.noticeTitle': 'Thông báo',
    'dialog.confirm': 'Xác nhận',

    'profile.basicInfo': 'Thông tin cơ bản',
    'profile.edit': 'Chỉnh sửa',
    'profile.cancelEdit': 'Hủy chỉnh sửa',
    'profile.systemId': 'ID Hệ thống',
    'profile.studentCode': 'Mã SV/GV',
    'profile.faculty': 'Khoa/Ngành',
    'profile.role': 'Vai trò',
    'profile.creditStatus': 'Điểm tín nhiệm / Trạng thái',
    'profile.active': 'Hoạt động',
    'profile.editableInfo': 'Thông tin có thể can thiệp',
    'profile.fullName': 'Họ tên',
    'profile.phone': 'Số điện thoại',
    'profile.birthDate': 'Ngày sinh',
    'profile.address': 'Địa chỉ',
    'profile.selectFaculty': 'Chọn khoa',
    'profile.avatarOptions': 'Tùy chọn ảnh đại diện',
    'profile.viewAvatar': 'Xem ảnh lớn',
    'profile.updateAvatar': 'Cập nhật ảnh mới',
    'profile.uploading': 'Đang tải lên...',
    'profile.avatarUpdated': 'Cập nhật ảnh đại diện thành công!',
    'profile.avatarUpdateFailed': 'Cập nhật ảnh thất bại',
    'profile.updateSuccess': 'Cập nhật thông tin thành công!',
    'profile.updateFailed': 'Cập nhật thất bại',
    'profile.loadFailed': 'Không thể tải thông tin người dùng.',

    'myBooks.title': 'Sách của tôi',
    'myBooks.subtitle':
      'Theo dõi sách chờ lấy, đang mượn và đã trả.',
    'myBooks.tabAll': 'Tất cả',
    'myBooks.tabWaiting': 'Sách chờ lấy',
    'myBooks.tabBorrowing': 'Sách đang mượn',
    'myBooks.tabReturned': 'Sách đã trả',
    'myBooks.tabCancelled': 'Sách đã hủy',
    'myBooks.current': 'Đang mượn',
    'myBooks.history': 'Lịch sử',
    'myBooks.borrowedBooks': 'Sách đang mượn',
    'myBooks.overdueBooks': 'Sách quá hạn',
    'myBooks.dueSoon': 'Sắp đến hạn (≤3 ngày)',
    'myBooks.totalTransactions': 'Tổng giao dịch',
    'myBooks.returned': 'Đã trả',
    'myBooks.finedTimes': 'Lần bị phạt',
    'myBooks.emptyCurrent': 'Bạn chưa mượn sách nào.',
    'myBooks.emptyHistory': 'Chưa có lịch sử mượn trả.',
    'myBooks.emptyAll': 'Bạn chưa có giao dịch mượn sách nào.',
    'myBooks.emptyWaiting': 'Không có sách nào đang chờ lấy.',
    'myBooks.emptyBorrowing': 'Không có sách nào đang mượn.',
    'myBooks.emptyReturned': 'Chưa có sách đã trả.',
    'myBooks.emptyCancelled': 'Chưa có sách đã hủy.',
    'myBooks.searchPlaceholder': 'Tìm theo tên sách...',
    'myBooks.sortNewest': 'Mới nhất',
    'myBooks.sortOldest': 'Cũ nhất',
    'myBooks.showingCount': 'Đang hiển thị',
    'myBooks.noSearchResults': 'Không tìm thấy sách khớp với từ khóa.',
    'myBooks.fineBlockTitle': 'Giao dịch có phí phạt',
    'myBooks.noFineBlockTitle': 'Không có phí phạt',
    'myBooks.noFineBlockDesc': 'Bạn chưa có giao dịch nào phát sinh phí phạt.',
    'myBooks.finedTransactionsShort': 'giao dịch',
    'myBooks.fromNotification': 'Từ thông báo',
    'myBooks.pickupDeadline': 'Hạn lấy',
    'myBooks.borrowedDate': 'Ngày mượn',
    'myBooks.dueDate': 'Hạn trả',
    'myBooks.returnedDate': 'Ngày trả',
    'myBooks.remaining': 'còn',
    'myBooks.overBy': 'quá',
    'myBooks.days': 'ngày',
    'myBooks.fine': 'Phí phạt',
    'myBooks.transactions': 'giao dịch',
    'myBooks.transactionId': 'Mã giao dịch',
    'myBooks.location': 'Vị trí',
    'myBooks.borrowSlip': 'Phiếu mượn sách',
    'myBooks.qrInstruction': 'Đưa mã QR này cho thủ thư để nhận sách.',
    'myBooks.pickupDeadlineTitle': 'Hạn chót đến lấy sách',
    'myBooks.status.waiting': 'Chờ lấy sách',
    'myBooks.status.borrowing': 'Đang mượn',
    'myBooks.status.overdue': 'Quá hạn',
    'myBooks.status.returned': 'Đã trả',
    'myBooks.status.cancelled': 'Đã huỷ',

    'dashboard.borrowedShort': 'Mượn',
    'dashboard.libraryHours': 'Giờ mở cửa thư viện',
    'dashboard.openNow': 'Đang mở cửa',
    'dashboard.borrowingSub': 'Sách đang trong tay',
    'dashboard.waitingSub': 'Cần đến thư viện nhận',
    'dashboard.overdueSub': 'Cần trả gấp',
    'dashboard.dueSoonSub': 'Còn ≤ 3 ngày',
    'dashboard.greeting': 'Xin chào',
    'dashboard.you': 'bạn',
    'dashboard.attentionPrefix': 'Bạn có',
    'dashboard.attentionSuffix': 'cần chú ý - sắp đến hạn hoặc quá hạn.',
    'dashboard.borrowingPrefix': 'Bạn đang mượn',
    'dashboard.borrowingSuffix': 'Tiếp tục đọc sách nào!',
    'dashboard.welcomeBack':
      'Chào mừng trở lại thư viện Library74. Khám phá sách mới ngay!',
    'dashboard.welcomeShort': 'Chào mừng trở lại',
    'dashboard.viewMyBooks': 'Xem sách đang mượn',
    'dashboard.dueBooksTitle': 'Sách sắp đến hạn',
    'dashboard.dueBooksDesc':
      'Các sách cần trả sớm nhất, ưu tiên theo ngày hạn',
    'dashboard.noDueBooksTitle': 'Tuyệt vời! Không có sách nào sắp đến hạn.',
    'dashboard.noDueBooksDesc': 'Bạn đang quản lý sách rất tốt.',
    'dashboard.pendingReservationsTitle': 'Đặt trước đang chờ',
    'dashboard.pendingReservationsDesc':
      'Theo dõi hàng chờ và sách đã sẵn sàng để nhận',
    'dashboard.monFri': 'Thứ Hai - Thứ Sáu',
    'dashboard.saturday': 'Thứ Bảy',
    'dashboard.sunday': 'Chủ Nhật',
    'dashboard.satSun': 'Thứ Bảy - Chủ Nhật',
    'dashboard.closed': 'ĐÓNG CỬA',
    'dashboard.supportTitle': 'Liên hệ hỗ trợ',
    'dashboard.supportDesc': 'Chúng tôi luôn sẵn sàng giúp đỡ',

    'reservations.title': 'Danh sách đặt trước',
    'reservations.subtitle': 'Theo dõi trạng thái sách bạn đã đặt.',
    'reservations.total': 'Tổng',
    'reservations.pending': 'Đang chờ',
    'reservations.ready': 'Sẵn sàng nhận',
    'reservations.empty': 'Bạn chưa đặt trước sách nào.',
    'reservations.loadFailed': 'Không thể tải danh sách đặt trước',
    'reservations.cancelSuccess': 'Đã hủy đặt trước',
    'reservations.status.pending': 'Đang chờ',
    'reservations.status.ready': 'Sẵn sàng nhận',
    'reservations.status.cancelled': 'Đã hủy',
    'reservations.status.expired': 'Hết hạn',
    'reservations.status.completed': 'Hoàn thành',
    'reservations.cancelReadyTitle': 'Hủy sách đã sẵn sàng?',
    'reservations.cancelTitle': 'Xác nhận hủy đặt trước',
    'reservations.cancelReadyPrefix': 'Sách',
    'reservations.cancelReadySuffix':
      'đang chờ bạn nhận. Nếu hủy, sách sẽ được chuyển cho người tiếp theo trong hàng chờ.',
    'reservations.cancelConfirmPrefix': 'Bạn có chắc muốn hủy đặt trước',
    'reservations.cancelConfirmSuffix': 'Vị trí hàng chờ sẽ bị mất.',
    'reservations.willPickup': 'Tôi sẽ đến lấy',
    'reservations.cancelAction': 'Hủy đặt trước',
    'reservations.qrTitle': 'Phiếu nhận sách đặt trước',
    'reservations.qrDesc': 'Đưa mã QR này cho thủ thư để xác nhận nhận sách.',
    'reservations.reservationId': 'Mã đặt trước',
    'reservations.branch': 'Chi nhánh',
    'reservations.shelf': 'Giá',
    'reservations.pickupDeadlineTitle': 'Hạn chót đến lấy sách',
    'reservations.reservedDate': 'Đặt ngày',
    'reservations.preferredBranch': 'Cơ sở ưu tiên',
    'reservations.anyBranch': 'Bất kỳ',
    'reservations.anyBranchFull': 'Bất kỳ cơ sở',
    'reservations.queuePosition': 'Vị trí hàng chờ',
    'reservations.queueShort': 'Hàng chờ',
    'reservations.pickupDeadline': 'Hạn nhận',
    'reservations.readyQuestion':
      'Sách đã sẵn sàng - bạn có muốn đến lấy không?',
    'reservations.noCancel': 'Không, hủy đặt',
    'reservations.viewQr': 'Xem mã QR nhận sách',
    'reservations.noteTitle': 'Lưu ý về đặt trước',
    'reservations.noteLimitPrefix': 'Bạn chỉ được đặt trước tối đa',
    'reservations.noteLimitSuffix': 'cùng lúc.',
    'reservations.notePickup': 'Khi sách sẵn sàng, bạn có',
    'reservations.hours': 'giờ',
    'reservations.notePickupSuffix': 'để đến nhận tại chi nhánh đã chọn.',
    'reservations.noteNotify':
      'Hệ thống sẽ gửi thông báo khi sách của bạn đã sẵn sàng.',
    'reservations.noteCancelPrefix': 'Nếu không còn nhu cầu, vui lòng nhấn',
    'reservations.noteCancelSuffix': 'để nhường lượt cho người sau.',

    'forgot.emailRequired': 'Vui lòng nhập email',
    'forgot.emailInvalid':
      'Email sai định dạng. Vui lòng dùng email Gmail.',
    'forgot.title': 'Quên mật khẩu?',
    'forgot.subtitle':
      'Nhập email của bạn, chúng tôi sẽ gửi link đặt lại mật khẩu.',
    'forgot.schoolEmail': 'Email',
    'forgot.emailPlaceholder': 'Ví dụ: yourname@gmail.com',
    'forgot.sending': 'Đang gửi...',
    'forgot.sendLink': 'Gửi link xác nhận',
    'forgot.checkEmailTitle': 'Kiểm tra email của bạn',
    'forgot.checkEmailPrefix': 'Chúng tôi đã gửi link đặt lại mật khẩu đến',
    'forgot.checkEmailDesc':
      'Vui lòng kiểm tra hộp thư đến (và hộp thư Spam) để tiếp tục.',
    'forgot.backToLogin': 'Quay lại trang Đăng nhập',

    'contact.toastSuccess': 'Đã ghi nhận tin nhắn liên hệ.',
    'contact.title': 'Liên hệ với chúng tôi',
    'contact.subtitle': 'Chúng tôi luôn sẵn sàng lắng nghe và hỗ trợ bạn',
    'contact.infoTitle': 'Thông tin liên hệ',
    'contact.address': 'Địa chỉ',
    'contact.addressLine1': 'Trường Đại học Bách khoa - ĐHQG-HCM',
    'contact.addressLine2': '268 Lý Thường Kiệt, Quận 10',
    'contact.addressLine3': 'TP. Hồ Chí Minh',
    'contact.phone': 'Điện thoại',
    'contact.tapToCall': 'Nhấn để gọi ngay',
    'contact.workingHours': 'Giờ làm việc',
    'contact.weekdays': 'Thứ 2 - Thứ 6',
    'contact.saturday': 'Thứ 7',
    'contact.sunday': 'Chủ nhật',
    'contact.connectTitle': 'Kết nối với chúng tôi',
    'contact.formTitle': 'Gửi tin nhắn cho chúng tôi',
    'contact.successTitle': 'Gửi thành công!',
    'contact.successDesc':
      'Phiếu hỗ trợ đã được mở. Nếu bạn đang đăng nhập, bạn có thể theo dõi và trao đổi tiếp trong Hộp thư liên hệ.',
    'contact.fullName': 'Họ và tên',
    'contact.fullNamePlaceholder': 'Nhập họ và tên',
    'contact.subject': 'Chủ đề',
    'contact.subjectPlaceholder': 'Nhập chủ đề',
    'contact.message': 'Nội dung',
    'contact.messagePlaceholder': 'Nhập nội dung tin nhắn của bạn...',
    'contact.sendMessage': 'Gửi tin nhắn',
    'contact.map': 'Bản đồ',
    'contact.mapTitle': 'Bản đồ Trường Đại học Bách khoa TP.HCM',

    'checkEmail.title': 'Kiểm tra email',
    'checkEmail.sent': 'Chúng tôi đã gửi một email xác nhận tài khoản cho bạn.',
    'checkEmail.activatePrefix': 'Vui lòng nhấn vào liên kết trong email để',
    'checkEmail.activateStrong': 'kích hoạt tài khoản',
    'checkEmail.activateSuffix': 'của bạn trước khi tiến hành đăng nhập.',
    'checkEmail.tipPrefix':
      'Nếu bạn không thấy email trong hộp thư đến, vui lòng kiểm tra thêm ở thư mục',
    'checkEmail.junk': 'Thư rác',
    'checkEmail.login': 'Tiến hành Đăng nhập',
    'verifySuccess.title': 'Xác minh thành công!',
    'verifySuccess.desc1':
      'Cảm ơn bạn đã xác minh địa chỉ email. Tài khoản của bạn đã được kích hoạt thành công.',
    'verifySuccess.desc2':
      'Bây giờ bạn đã có thể đăng nhập vào hệ thống để bắt đầu khám phá các tính năng của thư viện.',
    'verifySuccess.loginNow': 'Đăng nhập ngay',
    'oauth.missingCode': 'Thiếu mã code từ Google',
    'oauth.failedTitle': 'Đăng nhập thất bại',
    'oauth.backToLogin': 'Quay lại trang đăng nhập',
    'oauth.processingTitle': 'Đang xử lý đăng nhập Google...',
    'oauth.processingDesc': 'Vui lòng chờ trong giây lát',

    'wishlist.title': 'Danh sách yêu thích của bạn',
    'wishlist.savedCount': '{count} cuốn sách đã lưu',
    'wishlist.noBooks': 'Chưa có sách nào.',
    'wishlist.emptyTitle': 'Danh sách yêu thích trống',
    'wishlist.emptyDesc':
      'Vào trang chi tiết sách và nhấn thêm vào yêu thích để lưu sách',
    'wishlist.explore': 'Khám phá sách',
    'wishlist.loadFailed': 'Không thể tải danh sách yêu thích.',
    'wishlist.removed': 'Đã xóa khỏi danh sách yêu thích.',
    'wishlist.removeTitle': 'Xóa khỏi danh sách yêu thích',
    'wishlist.clearAll': 'Xóa tất cả',
    'wishlist.clearAllTitle': 'Xóa tất cả danh sách yêu thích',
    'wishlist.clearAllConfirm':
      'Bạn chắc chắn muốn xóa toàn bộ {count} sách khỏi danh sách yêu thích? Hành động này không thể hoàn tác.',
    'wishlist.clearAllSuccess': 'Đã xóa toàn bộ danh sách yêu thích.',

    'fines.title': 'Phí phạt',
    'fines.subtitle': 'Quản lý các khoản phí phạt của bạn.',
    'fines.unpaid': 'Chưa thanh toán',
    'fines.paid': 'Đã thanh toán',
    'fines.total': 'Tổng cộng',
    'fines.noUnpaid': 'Không có phí phạt nào chưa thanh toán.',
    'fines.noPaid': 'Chưa có lịch sử thanh toán.',
    'fines.items': 'khoản phạt',
    'fines.paymentGuide': 'Hướng dẫn thanh toán',
    'fines.payDirect': 'Thanh toán trực tiếp',
    'fines.payDirectDesc':
      'Đến quầy thủ thư tại thư viện trong giờ hành chính.',
    'fines.note': 'Lưu ý',
    'fines.noteDesc': 'Phí phạt chưa thanh toán sẽ khóa quyền mượn sách mới.',
    'fines.type.overdue': 'Quá hạn',
    'fines.type.damaged': 'Hư hỏng',
    'fines.type.lost': 'Mất sách',

    'notifications.title': 'Thông báo & Nhắc nhở',
    'notifications.subtitle': 'Cập nhật quan trọng cho bạn',
    'notifications.markAllRead': 'Đánh dấu tất cả là đã đọc',
    'notifications.refresh': 'Làm mới',
    'notifications.empty': 'Bạn chưa có thông báo nào.',
    'notifications.viewDetails': 'Xem chi tiết',
    'notifications.loadMore': 'Tải thêm thông báo',

    'bookDetail.notFound': 'Không tìm thấy thông tin ấn phẩm',
    'bookDetail.backHome': 'Quay lại trang chủ',
    'bookDetail.available': 'Có sẵn',
    'bookDetail.borrowed': 'Đang mượn',
    'bookDetail.saved': 'Đã lưu',
    'bookDetail.wishlist': 'Danh sách yêu thích',
    'bookDetail.share': 'Chia sẻ',
    'bookDetail.citation': 'Trích dẫn tài liệu',
    'bookDetail.author': 'Tác giả',
    'bookDetail.year': 'Năm',
    'bookDetail.publisher': 'NXB',
    'bookDetail.reviews': 'Đánh giá',
    'bookDetail.reserve': 'Đặt trước',
    'bookDetail.aiSubtitle': 'Phân tích thông minh bởi AI',
    'bookDetail.noAiSummary': 'Chưa có AI Summary cho ấn phẩm này.',
    'bookDetail.targetAudience': 'Đối tượng phù hợp',
    'bookDetail.copyStatus': 'Tình trạng bản sao',
    'bookDetail.availableCount': 'Có sẵn',
    'bookDetail.borrowedCount': 'Đang mượn',
    'bookDetail.notice': 'Thông báo',
    'bookDetail.totalCopiesNotice':
      'Có {total} bản ({available} bản khả dụng).',
    'bookDetail.allBorrowedNotice':
      'Hiện đã được mượn hết. Vui lòng đặt trước để giữ chỗ.',
    'bookDetail.condition': 'Tình trạng',
    'bookDetail.location': 'Vị trí',
    'bookDetail.status': 'Trạng thái',
    'bookDetail.action': 'Hành động',
    'bookDetail.loadingCopies': 'Đang tải danh sách bản sao...',
    'bookDetail.printedBook': 'Sách in',
    'bookDetail.borrowNow': 'Mượn ngay',
    'bookDetail.unavailable': 'Không khả dụng',
    'bookDetail.noCopies': 'Không có bản sao nào',
    'bookDetail.showingCopies':
      'Hiển thị {from} - {to} trong tổng số {total} bản sao',
    'bookDetail.overview': 'Tổng quan',
    'bookDetail.toc': 'Mục lục',
    'bookDetail.related': 'Sách liên quan',
    'bookDetail.description': 'Mô tả chi tiết',
    'bookDetail.noDescription': 'Chưa có mô tả.',
    'bookDetail.publicationInfo': 'Thông tin xuất bản',
    'bookDetail.callNumber': 'Mã xếp giá (DDC)',
    'bookDetail.pages': 'Số trang',
    'bookDetail.pageUnit': 'trang',
    'bookDetail.edition': 'Phiên bản',
    'bookDetail.editionValue': 'Lần xuất bản thứ {edition}',
    'bookDetail.publicationYear': 'Năm xuất bản',
    'bookDetail.language': 'Ngôn ngữ',
    'bookDetail.sizeWeight': 'Kích thước / Trọng lượng',
    'bookDetail.tags': 'Từ khóa (Tags)',
    'bookDetail.noToc': 'Chưa có mục lục cho ấn phẩm này.',
    'bookDetail.invalidToc': 'Dữ liệu mục lục không hợp lệ.',
    'bookDetail.chapters': 'chương',
    'bookDetail.noPageNumber': 'Không có số trang',
    'bookDetail.pageShort': 'tr.',
    'bookDetail.similarBooks': 'Các loại sách tương tự sách này',
    'bookDetail.exploreMore': 'Khám phá thêm',
    'bookDetail.sameTopic': 'Sách cùng chủ đề',
    'bookDetail.viewAll': 'Xem tất cả',
    'bookDetail.unknownAuthor': 'Chưa rõ tác giả',
    'bookDetail.availableCopiesShort': '{count} bản có sẵn',
    'bookDetail.noSimilar': 'Chưa có dữ liệu sách tương tự cho ấn phẩm này.',
    'bookDetail.dueExpected': 'Trả dự kiến',
    'bookDetail.reserveTitle': 'Đặt trước sách',
    'bookDetail.reserveSubtitle': 'Chọn cơ sở bạn muốn nhận sách',
    'bookDetail.anyBranch': 'Bất kỳ cơ sở',
    'bookDetail.anyBranchSub': 'Nhận sách tại cơ sở nào trả trước',
    'bookDetail.noCopiesReserve':
      'Ấn phẩm này chưa có bản sao nào trong thư viện. Hệ thống sẽ thông báo khi có sách.',
    'bookDetail.availableAtBranch':
      'Hiện có bản sao sẵn sàng mượn tại cơ sở này — bạn có thể đến thư viện mượn trực tiếp mà không cần đặt trước.',
    'bookDetail.processing': 'Đang xử lý...',
    'bookDetail.confirmReserve': 'Xác nhận đặt trước',
    'bookDetail.loginRequired':
      'Vui lòng đăng nhập tài khoản sinh viên để {action}.',
    'bookDetail.actionWishlist': 'lưu sách vào wishlist',
    'bookDetail.actionReserve': 'đặt trước sách',
    'bookDetail.actionBorrow': 'mượn sách',
    'bookDetail.removedWishlist': 'Đã xóa khỏi danh sách yêu thích.',
    'bookDetail.addedWishlist': 'Đã thêm vào danh sách yêu thích!',
    'bookDetail.tryAgain': 'Có lỗi xảy ra, vui lòng thử lại.',
    'bookDetail.shareText': 'Xem sách "{title}" trên Library74',
    'bookDetail.linkCopied': 'Đã sao chép liên kết sách.',
    'bookDetail.unknownPublisher': 'Không rõ nhà xuất bản',
    'bookDetail.citationCopied': 'Đã sao chép trích dẫn tài liệu.',
    'bookDetail.reserveSuccess':
      'Đặt trước thành công! Chúng tôi sẽ thông báo khi sách sẵn sàng.',
    'bookDetail.reserveAvailableError':
      'Sách đang có sẵn tại cơ sở này — bạn có thể đến thư viện mượn trực tiếp.',
    'bookDetail.reservePendingError':
      'Bạn đã có đặt trước đang chờ cho ấn phẩm này rồi.',
    'bookDetail.reserveNoCopyError':
      'Hiện tại chi nhánh này chưa có bản sao nào của sách, vui lòng chọn chi nhánh khác.',
    'bookDetail.reserveLimitError':
      'Bạn đã đạt giới hạn tối đa 2 cuốn sách đặt trước.',
    'bookDetail.reserveFineError':
      'Bạn đang có khoản phí chưa thanh toán. Vui lòng hoàn tất nghĩa vụ để sử dụng tính năng đặt trước.',
    'bookDetail.reserveFailed': 'Không thể đặt trước lúc này.',
    'bookDetail.confirmBorrow': 'Bạn có chắc chắn muốn mượn sách này?',
    'bookDetail.borrowFailed':
      'Không thể mượn sách lúc này. Vui lòng thử lại sau.',
    'bookDetail.borrowSuccess': 'Yêu cầu mượn thành công!',
    'bookDetail.qrInstruction':
      'Vui lòng đưa mã QR này cho thủ thư để nhận sách.',
    'bookDetail.transactionId': 'Mã giao dịch',
    'bookDetail.pickupDeadline': 'Hạn chót đến lấy sách',
    'bookDetail.status.available': 'Có sẵn',
    'bookDetail.status.reserved': 'Đã có người đặt',
    'bookDetail.status.borrowed': 'Đang được mượn',
    'bookDetail.status.maintenance': 'Đang bảo trì',
    'bookDetail.status.lost': 'Mất / Thất lạc',
    'bookDetail.reviewBasedOn': 'Dựa trên {count} đánh giá',
    'bookDetail.writeReview': 'Viết đánh giá của bạn',
    'bookDetail.yourRating': 'Đánh giá của bạn',
    'bookDetail.comment': 'Nhận xét',
    'bookDetail.commentPlaceholder':
      'Chia sẻ trải nghiệm của bạn về cuốn sách này...',
    'bookDetail.submitReview': 'Gửi đánh giá',
    'bookDetail.communityReviews': 'Đánh giá từ cộng đồng',
    'bookDetail.loadingReviews': 'Đang tải đánh giá...',
    'bookDetail.noReviews': 'Chưa có đánh giá nào cho ấn phẩm này.',
    'bookDetail.helpful': 'Hữu ích',
    'bookDetail.reply': 'Trả lời',
    'bookDetail.reviewRequired': 'Vui lòng nhập nhận xét của bạn.',
    'bookDetail.reviewSuccess': 'Gửi đánh giá thành công!',
    'bookDetail.reviewFailed': 'Gửi đánh giá thất bại.',

    'home.aiPowered': 'Nhập mô tả. Phá giới hạn. Chạm tri thức.',
    'home.heroTitlePrefix': 'Tìm sách bằng',
    'home.heroTitleHighlight': 'ngôn ngữ tự nhiên',
    'home.heroDescription':
      'Khám phá hàng ngàn tài liệu học thuật với công nghệ tìm kiếm ngữ nghĩa. Không cần từ khóa chính xác, chỉ cần mô tả những gì bạn muốn tìm.',
    'home.searchPlaceholder':
      'Nhập tên sách, tác giả, ISBN hoặc mô tả nội dung...',
    'home.recentSearches': 'Tìm gần đây:',
    'home.suggestions': 'Gợi ý:',
    'home.viewNewest': 'Xem tất cả sách mới',
    'home.exploreTopics': 'Khám phá theo chủ đề',
    'home.availableMaterials': 'Tài liệu khả dụng',
    'home.activeStudents': 'Sinh viên đang sử dụng',
    'home.forYouEyebrow': 'Dành riêng cho bạn',
    'home.forYouTitle': 'Gợi ý cho bạn',
    'home.forYouSubtitle':
      'Được cá nhân hóa dựa trên sở thích và lịch sử của bạn',
    'home.loginForRecommendations': 'Đăng nhập để xem gợi ý cá nhân hóa.',
    'home.emptyRecommendations':
      'Hãy mượn hoặc lưu sách để nhận gợi ý phù hợp hơn.',
    'home.categoriesEyebrow': 'Danh mục phong phú',
    'home.categoriesTitle': 'Khám phá theo Chủ đề',
    'home.categoriesSubtitle':
      'Tìm kiếm tài liệu theo lĩnh vực chuyên môn của bạn',
    'home.noCategories': 'Chưa có danh mục nào trong hệ thống.',
    'home.allTopics': 'Xem tất cả chủ đề',
    'home.newBooks': 'Sách mới',
    'home.newUpdated': 'Mới cập nhật',
    'home.loadingNewBooks': 'Đang tải sách mới...',
    'home.noNewBooks': 'Không có sách mới nào.',
    'home.newTag': 'MỚI',
    'home.popularBooks': 'Mượn nhiều nhất',
    'home.trending': 'Xu hướng',
    'home.loadingPopularBooks': 'Đang tải sách mượn nhiều...',
    'home.noPopularBooks': 'Không có sách mượn nhiều.',
    'home.borrowCount': 'lượt mượn',
    'home.aiTechnology': 'CÔNG NGHỆ AI',
    'home.aiHelpTitle': 'AI giúp gì cho bạn?',
    'home.aiHelpDesc':
      'Trải nghiệm sức mạnh của trí tuệ nhân tạo trong việc tìm kiếm và khám phá tri thức học thuật một cách hiệu quả.',
    'home.contextTitle': 'Hiểu ngữ cảnh',
    'home.contextDesc':
      'AI phân tích và hiểu ý nghĩa sâu xa của câu truy vấn, không chỉ dừng lại ở việc khớp từ khóa đơn thuần. Kết quả tìm kiếm chính xác hơn nhiều so với phương pháp truyền thống.',
    'home.behaviorTitle': 'Học từ hành vi',
    'home.behaviorDesc':
      'Hệ thống ghi nhận sở thích đọc, lịch sử mượn và tương tác của bạn để ngày càng hiểu rõ nhu cầu. Mỗi lần sử dụng, gợi ý càng trở nên phù hợp và cá nhân hóa hơn.',
    'home.discoveryTitle': 'Khám phá thông minh',
    'home.discoveryDesc':
      'AI tự động kết nối các tài liệu liên quan, gợi ý các chủ đề mở rộng và giúp bạn khám phá những nguồn tài liệu mà bạn chưa từng nghĩ tới nhưng rất hữu ích.',
    'home.tryAiTitle': 'Trải nghiệm sức mạnh AI ngay hôm nay',
    'home.tryAiDesc':
      'Sinh viên đang sử dụng Library74 để cải thiện hiệu quả học tập. Đăng ký miễn phí và khám phá cách AI có thể giúp bạn tìm kiếm tri thức nhanh hơn.',
    'home.freeForStudents': 'Miễn phí 100% cho sinh viên',
    'home.unlimitedSearch': 'Không giới hạn số lượng tìm kiếm',
    'home.support247': 'Hỗ trợ 24/7',
    'home.freeRegister': 'Đăng ký miễn phí',
    'home.statsTitle': 'Con số ấn tượng',
    'home.statsSubtitle': 'Library74 đang phục vụ cộng đồng sinh viên mỗi ngày',
    'home.materials': 'Tài liệu',
    'home.users': 'Người dùng',
    'home.borrows': 'Lượt mượn',
    'home.satisfaction': 'Hài lòng',
    'home.testimonialsEyebrow': 'ĐÁNH GIÁ TỪ NGƯỜI DÙNG',
    'home.testimonialsTitle': 'Người đọc nói gì về chúng tôi',
    'home.testimonialsSubtitle':
      'Những phản hồi chân thực từ cộng đồng người dùng',
    'home.reviewCountLabel': 'đánh giá',
    'home.satisfiedLabel': 'hài lòng',
    'home.editSystemReview': 'Chỉnh sửa đánh giá',
    'home.reviewSystem': 'Đánh giá hệ thống',
    'home.submitSystemReview': 'Gửi đánh giá',
    'home.viewAllReviews': 'Xem tất cả đánh giá',
    'home.noSystemReviews': 'Chưa có đánh giá hệ thống nào.',
    'home.noSystemReviewsDesc':
      'Các phản hồi tại đây chỉ hiển thị khi người dùng thật gửi đánh giá.',
    'home.defaultReviewQuote': 'Đánh giá {rating}/5 cho trải nghiệm Library74.',
    'home.reviewModalTitle': 'Đánh giá trải nghiệm của bạn',
    'home.reviewModalEditTitle': 'Chỉnh sửa đánh giá hệ thống',
    'home.reviewModalDesc':
      'Mỗi tài khoản có một đánh giá và có thể cập nhật bất kỳ lúc nào.',
    'home.reviewSatisfactionLevel': 'Mức độ hài lòng',
    'home.reviewSatisfactionRule':
      'Từ 3 sao trở lên được tính là người dùng hài lòng trong thống kê hệ thống.',
    'home.reviewYourThoughts': 'Cảm nhận của bạn',
    'home.reviewPlaceholder':
      'Điều gì khiến bạn hài lòng hoặc muốn Library74 cải thiện?',
    'home.reviewWritingHint':
      'Review tốt nhất là cụ thể, ngắn gọn và chân thực.',
    'home.reviewRequired': 'Vui lòng nhập cảm nhận của bạn về hệ thống.',
    'home.reviewSaveFailed': 'Không thể lưu đánh giá lúc này.',
    'home.readyTitle': 'Sẵn sàng bắt đầu?',
    'home.readyDesc':
      'Tham gia cùng cộng đồng sinh viên đang sử dụng Library74 để nâng cao hiệu quả học tập.',
    'home.exploreNow': 'Khám phá ngay',
    'home.noCredit':
      'Không cần thẻ tín dụng • Miễn phí vĩnh viễn cho sinh viên • Bắt đầu trong 30 giây',

    'categories.title': 'Danh mục sách',
    'categories.subtitle':
      'Khám phá các đầu sách theo danh mục đang có trong hệ thống thư viện.',
    'categories.searchPlaceholder': 'Tìm kiếm danh mục...',
    'categories.unnamed': 'Danh mục chưa đặt tên',
    'categories.parent': 'Thuộc nhóm:',
    'categories.defaultDescription':
      'Xem các tài liệu đang được phân loại trong danh mục này.',
    'categories.noMatch': 'Không tìm thấy danh mục nào phù hợp.',
    'categories.realCategories': 'Danh mục thực tế',
    'categories.bookClassifications': 'Lượt phân loại sách',
    'categories.onlineLookup': 'Tra cứu trực tuyến',
  },
  en: {
    'brand.name': 'Library74',
    'brand.tagline': 'NEXT-GEN DISCOVERY',
    'common.loading': 'Loading...',
    'common.cancel': 'Cancel',
    'common.saveChanges': 'Save changes',
    'common.saving': 'Saving...',
    'common.search': 'Search',
    'common.searchBooks': 'Search books...',
    'common.viewAll': 'View all',
    'common.viewDetails': 'View details',
    'common.learnMore': 'Learn more',
    'common.books': 'books',
    'common.book': 'Book',
    'common.or': 'or',
    'common.availableCopies': 'available copies',
    'common.copies': 'copies',
    'common.logout': 'Log out',
    'common.dashboard': 'Dashboard',
    'common.back': 'Back',
    'common.language': 'Language',
    'common.vietnamese': 'Vietnamese',
    'common.english': 'English',

    'nav.home': 'Home',
    'nav.search': 'Search',
    'nav.categories': 'Categories',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.login': 'Log in',
    'nav.register': 'Sign up',
    'nav.enterDashboard': 'Dashboard',

    'footer.description':
      'A next-gen smart library platform elevating academic discovery and knowledge access for readers.',
    'footer.discover': 'Explore',
    'footer.support': 'Support',
    'footer.contact': 'Contact',
    'footer.newBooks': 'New books',
    'footer.popularBooks': 'Most borrowed',
    'footer.guide': 'User guide',
    'footer.faq': 'FAQ',
    'footer.terms': 'Terms of use',
    'footer.privacy': 'Privacy policy',
    'footer.serviceTerms': 'Service terms',
    'footer.cookie': 'Cookie policy',
    'footer.address':
      'Ho Chi Minh City University of Technology - VNU-HCM\n268 Ly Thuong Kiet, Ward 14, District 10, HCMC',

    'user.section.overview': 'Overview',
    'user.section.personal': 'Personal library',
    'user.section.settings': 'Settings',
    'user.borrowedBooks': 'Borrowed books',
    'user.reservations': 'Reservations',
    'user.wishlist': 'Wishlist',
    'user.fines': 'Fines',
    'user.contactSupport': 'Contact & support',
    'user.profile': 'Personal information',
    'user.settings': 'Settings',

    'librarian.librarianPages': 'Librarian Portal',
    'librarian.mainMenu': 'Main menu',
    'librarian.system': 'System',
    'librarian.home': 'Dashboard',
    'librarian.circulation': 'Circulation',
    'librarian.books': 'Publications',
    'librarian.transactions': 'Transaction history',
    'librarian.copies': 'Copies',
    'librarian.contactInbox': 'Contact inbox',
    'librarian.reports': 'Executive reports',
    'librarian.publicView': 'Public view',
    'librarian.settings': 'Settings',
    'librarian.role': 'Librarian',
    'librarian.portalName': 'Librarian',

    'settings.title': 'Settings',
    'settings.subtitle': 'Customize your interface and account security',
    'settings.interface': 'Interface',
    'settings.theme': 'Theme',
    'settings.light': 'Light',
    'settings.dark': 'Dark',
    'settings.system': 'System',
    'settings.security': 'Security',
    'settings.changePassword': 'Change password',
    'settings.currentPassword': 'Current password',
    'settings.newPassword': 'New password',
    'settings.confirmPassword': 'Confirm new password',
    'settings.passwordHint':
      'Password must be at least 8 characters and include uppercase, lowercase, and numbers',
    'settings.fillPassword': 'Please fill in all password fields.',
    'settings.passwordLength': 'New password must be at least 8 characters.',
    'settings.passwordMismatch': 'Password confirmation does not match.',
    'settings.saved': 'Settings saved.',
    'settings.saveFailed': 'Unable to save settings.',

    'common.close': 'Close',
    'common.none': 'None',
    'common.systemError': 'System error',
    'common.showing': 'Showing',
    'common.in': 'in',
    'common.previous': 'Previous',
    'common.next': 'Next',
    'dialog.confirmTitle': 'Confirm action',
    'dialog.noticeTitle': 'Notice',
    'dialog.confirm': 'Confirm',

    'profile.basicInfo': 'Basic information',
    'profile.edit': 'Edit',
    'profile.cancelEdit': 'Cancel editing',
    'profile.systemId': 'System ID',
    'profile.studentCode': 'Student/Staff ID',
    'profile.faculty': 'Faculty/Major',
    'profile.role': 'Role',
    'profile.creditStatus': 'Credit score / Status',
    'profile.active': 'Active',
    'profile.editableInfo': 'Editable information',
    'profile.fullName': 'Full name',
    'profile.phone': 'Phone number',
    'profile.birthDate': 'Date of birth',
    'profile.address': 'Address',
    'profile.selectFaculty': 'Select faculty',
    'profile.avatarOptions': 'Avatar options',
    'profile.viewAvatar': 'View full-size image',
    'profile.updateAvatar': 'Update avatar',
    'profile.uploading': 'Uploading...',
    'profile.avatarUpdated': 'Avatar updated successfully!',
    'profile.avatarUpdateFailed': 'Avatar update failed',
    'profile.updateSuccess': 'Profile updated successfully!',
    'profile.updateFailed': 'Profile update failed',
    'profile.loadFailed': 'Unable to load user profile.',

    'myBooks.title': 'My books',
    'myBooks.subtitle':
      'Track books waiting for pickup, currently borrowed, and returned in one place',
    'myBooks.tabAll': 'All',
    'myBooks.tabWaiting': 'Waiting for pickup',
    'myBooks.tabBorrowing': 'Borrowed books',
    'myBooks.tabReturned': 'Returned books',
    'myBooks.tabCancelled': 'Cancelled books',
    'myBooks.current': 'Current',
    'myBooks.history': 'History',
    'myBooks.borrowedBooks': 'Borrowed books',
    'myBooks.overdueBooks': 'Overdue books',
    'myBooks.dueSoon': 'Due soon (≤3 days)',
    'myBooks.totalTransactions': 'Total transactions',
    'myBooks.returned': 'Returned',
    'myBooks.finedTimes': 'Fined transactions',
    'myBooks.emptyCurrent': 'You have no borrowed books.',
    'myBooks.emptyHistory': 'No borrowing history yet.',
    'myBooks.emptyAll': 'You do not have any borrowing transactions yet.',
    'myBooks.emptyWaiting': 'No books are waiting for pickup.',
    'myBooks.emptyBorrowing': 'No books are currently borrowed.',
    'myBooks.emptyReturned': 'No returned books yet.',
    'myBooks.emptyCancelled': 'No cancelled books yet.',
    'myBooks.searchPlaceholder': 'Search by book title...',
    'myBooks.sortNewest': 'Newest',
    'myBooks.sortOldest': 'Oldest',
    'myBooks.showingCount': 'Showing',
    'myBooks.noSearchResults': 'No books match your search.',
    'myBooks.fineBlockTitle': 'Transactions with fines',
    'myBooks.noFineBlockTitle': 'No fines',
    'myBooks.noFineBlockDesc': 'You do not have any transactions with fines.',
    'myBooks.finedTransactionsShort': 'transactions',
    'myBooks.fromNotification': 'From notification',
    'myBooks.pickupDeadline': 'Pickup deadline',
    'myBooks.borrowedDate': 'Borrowed date',
    'myBooks.dueDate': 'Due date',
    'myBooks.returnedDate': 'Returned date',
    'myBooks.remaining': 'remaining',
    'myBooks.overBy': 'overdue by',
    'myBooks.days': 'days',
    'myBooks.fine': 'Fine',
    'myBooks.transactions': 'transactions',
    'myBooks.transactionId': 'Transaction ID',
    'myBooks.location': 'Location',
    'myBooks.borrowSlip': 'Borrowing slip',
    'myBooks.qrInstruction':
      'Show this QR code to the librarian to pick up your book.',
    'myBooks.pickupDeadlineTitle': 'Pickup deadline',
    'myBooks.status.waiting': 'Waiting for pickup',
    'myBooks.status.borrowing': 'Borrowing',
    'myBooks.status.overdue': 'Overdue',
    'myBooks.status.returned': 'Returned',
    'myBooks.status.cancelled': 'Cancelled',

    'dashboard.borrowedShort': 'Borrowed',
    'dashboard.libraryHours': 'Library hours',
    'dashboard.openNow': 'Open now',
    'dashboard.borrowingSub': 'Books currently with you',
    'dashboard.waitingSub': 'Visit the library to pick up',
    'dashboard.overdueSub': 'Return urgently',
    'dashboard.dueSoonSub': 'Due in ≤ 3 days',
    'dashboard.greeting': 'Hello',
    'dashboard.you': 'you',
    'dashboard.attentionPrefix': 'You have',
    'dashboard.attentionSuffix': 'that need attention - due soon or overdue.',
    'dashboard.borrowingPrefix': 'You are borrowing',
    'dashboard.borrowingSuffix': 'Keep reading!',
    'dashboard.welcomeBack':
      'Welcome back to Library74 Library. Discover new books today!',
    'dashboard.welcomeShort': 'Welcome back',
    'dashboard.viewMyBooks': 'View my books',
    'dashboard.dueBooksTitle': 'Books due soon',
    'dashboard.dueBooksDesc':
      'Books that need to be returned first, ordered by due date',
    'dashboard.noDueBooksTitle': 'Great! No books are due soon.',
    'dashboard.noDueBooksDesc': 'You are managing your books well.',
    'dashboard.pendingReservationsTitle': 'Pending reservations',
    'dashboard.pendingReservationsDesc':
      'Track your queue and books ready for pickup',
    'dashboard.monFri': 'Monday - Friday',
    'dashboard.saturday': 'Saturday',
    'dashboard.sunday': 'Sunday',
    'dashboard.satSun': 'Saturday - Sunday',
    'dashboard.closed': 'CLOSED',
    'dashboard.supportTitle': 'Contact support',
    'dashboard.supportDesc': 'We are ready to help',

    'reservations.title': 'Reservations',
    'reservations.subtitle': 'Track the status of books you reserved',
    'reservations.total': 'Total',
    'reservations.pending': 'Pending',
    'reservations.ready': 'Ready for pickup',
    'reservations.empty': 'You have not reserved any books.',
    'reservations.loadFailed': 'Unable to load reservations',
    'reservations.cancelSuccess': 'Reservation cancelled.',
    'reservations.status.pending': 'Pending',
    'reservations.status.ready': 'Ready for pickup',
    'reservations.status.cancelled': 'Cancelled',
    'reservations.status.expired': 'Expired',
    'reservations.status.completed': 'Completed',
    'reservations.cancelReadyTitle': 'Cancel ready book?',
    'reservations.cancelTitle': 'Confirm cancellation',
    'reservations.cancelReadyPrefix': 'Book',
    'reservations.cancelReadySuffix':
      'is waiting for pickup. If you cancel, it will be assigned to the next reader in queue.',
    'reservations.cancelConfirmPrefix':
      'Are you sure you want to cancel the reservation for',
    'reservations.cancelConfirmSuffix': 'Your queue position will be lost.',
    'reservations.willPickup': 'I will pick it up',
    'reservations.cancelAction': 'Cancel reservation',
    'reservations.qrTitle': 'Reservation pickup slip',
    'reservations.qrDesc':
      'Show this QR code to the librarian to confirm pickup.',
    'reservations.reservationId': 'Reservation ID',
    'reservations.branch': 'Branch',
    'reservations.shelf': 'Shelf',
    'reservations.pickupDeadlineTitle': 'Pickup deadline',
    'reservations.reservedDate': 'Reserved on',
    'reservations.preferredBranch': 'Preferred branch',
    'reservations.anyBranch': 'Any',
    'reservations.anyBranchFull': 'Any branch',
    'reservations.queuePosition': 'Queue position',
    'reservations.queueShort': 'Queue',
    'reservations.pickupDeadline': 'Pickup deadline',
    'reservations.readyQuestion':
      'The book is ready - would you like to pick it up?',
    'reservations.noCancel': 'No, cancel it',
    'reservations.viewQr': 'View pickup QR',
    'reservations.noteTitle': 'Reservation notes',
    'reservations.noteLimitPrefix': 'You can reserve at most',
    'reservations.noteLimitSuffix': 'at the same time.',
    'reservations.notePickup': 'When a book is ready, you have',
    'reservations.hours': 'hours',
    'reservations.notePickupSuffix': 'to pick it up at the selected branch.',
    'reservations.noteNotify':
      'The system will notify you when your book is ready.',
    'reservations.noteCancelPrefix': 'If you no longer need it, please click',
    'reservations.noteCancelSuffix': 'so the next reader can be served.',

    'forgot.emailRequired': 'Please enter your email',
    'forgot.emailInvalid':
      'Invalid email. Please use a Gmail address.',
    'forgot.title': 'Forgot password?',
    'forgot.subtitle':
      'Enter your email and we will send a reset link.',
    'forgot.schoolEmail': 'Email',
    'forgot.emailPlaceholder': 'Example: yourname@gmail.com',
    'forgot.sending': 'Sending...',
    'forgot.sendLink': 'Send reset link',
    'forgot.checkEmailTitle': 'Check your email',
    'forgot.checkEmailPrefix': 'We sent a password reset link to',
    'forgot.checkEmailDesc':
      'Please check your inbox and spam folder to continue.',
    'forgot.backToLogin': 'Back to login',

    'contact.toastSuccess': 'Your contact message has been recorded.',
    'contact.title': 'Contact us',
    'contact.subtitle': 'We are always ready to listen and support you',
    'contact.infoTitle': 'Contact information',
    'contact.address': 'Address',
    'contact.addressLine1':
      'Ho Chi Minh City University of Technology - VNU-HCM',
    'contact.addressLine2': '268 Ly Thuong Kiet, District 10',
    'contact.addressLine3': 'Ho Chi Minh City',
    'contact.phone': 'Phone',
    'contact.tapToCall': 'Tap to call',
    'contact.workingHours': 'Working hours',
    'contact.weekdays': 'Monday - Friday',
    'contact.saturday': 'Saturday',
    'contact.sunday': 'Sunday',
    'contact.connectTitle': 'Connect with us',
    'contact.formTitle': 'Send us a message',
    'contact.successTitle': 'Sent successfully!',
    'contact.successDesc':
      'Your ticket is open. If you are signed in, you can track it and continue the conversation in Contact tickets.',
    'contact.fullName': 'Full name',
    'contact.fullNamePlaceholder': 'Enter your full name',
    'contact.subject': 'Subject',
    'contact.subjectPlaceholder': 'Enter a subject',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Enter your message...',
    'contact.sendMessage': 'Send message',
    'contact.map': 'Map',
    'contact.mapTitle': 'Map of Library74',

    'checkEmail.title': 'Check your email',
    'checkEmail.sent': 'We sent you an account verification email.',
    'checkEmail.activatePrefix': 'Please click the link in the email to',
    'checkEmail.activateStrong': 'activate your account',
    'checkEmail.activateSuffix': 'before logging in.',
    'checkEmail.tipPrefix':
      'If you do not see the email in your inbox, please also check',
    'checkEmail.junk': 'Junk',
    'checkEmail.login': 'Continue to login',
    'verifySuccess.title': 'Verification successful!',
    'verifySuccess.desc1':
      'Thank you for verifying your email address. Your account has been activated successfully.',
    'verifySuccess.desc2':
      'You can now log in and start exploring the library features.',
    'verifySuccess.loginNow': 'Log in now',
    'oauth.missingCode': 'Missing Google authorization code',
    'oauth.failedTitle': 'Login failed',
    'oauth.backToLogin': 'Back to login',
    'oauth.processingTitle': 'Processing Google login...',
    'oauth.processingDesc': 'Please wait a moment',

    'wishlist.title': 'Your wishlist',
    'wishlist.savedCount': '{count} saved books',
    'wishlist.noBooks': 'No books yet',
    'wishlist.emptyTitle': 'Your wishlist is empty',
    'wishlist.emptyDesc':
      'Open a book detail page and press Wishlist to save it',
    'wishlist.explore': 'Explore books',
    'wishlist.loadFailed': 'Unable to load wishlist.',
    'wishlist.removed': 'Removed from wishlist.',
    'wishlist.removeTitle': 'Remove from wishlist',
    'wishlist.clearAll': 'Clear all',
    'wishlist.clearAllTitle': 'Clear wishlist',
    'wishlist.clearAllConfirm':
      'Are you sure you want to remove all {count} books from your wishlist? This action cannot be undone.',
    'wishlist.clearAllSuccess': 'Wishlist cleared.',

    'fines.title': 'Fines',
    'fines.subtitle': 'Manage your library fines',
    'fines.unpaid': 'Unpaid',
    'fines.paid': 'Paid',
    'fines.total': 'Total',
    'fines.noUnpaid': 'You have no unpaid fines.',
    'fines.noPaid': 'No payment history yet.',
    'fines.items': 'fines',
    'fines.paymentGuide': 'Payment guide',
    'fines.payDirect': 'Pay at the library',
    'fines.payDirectDesc':
      'Visit the librarian desk during library opening hours.',
    'fines.note': 'Note',
    'fines.noteDesc': 'Unpaid fines will block new borrowing requests.',
    'fines.type.overdue': 'Overdue',
    'fines.type.damaged': 'Damaged book',
    'fines.type.lost': 'Lost book',

    'notifications.title': 'Notifications & reminders',
    'notifications.subtitle': 'Important updates for you',
    'notifications.markAllRead': 'Mark all as read',
    'notifications.refresh': 'Refresh',
    'notifications.empty': 'You have no notifications yet.',
    'notifications.viewDetails': 'View details',
    'notifications.loadMore': 'Load more notifications',

    'bookDetail.notFound': 'Publication not found',
    'bookDetail.backHome': 'Back to home',
    'bookDetail.available': 'Available',
    'bookDetail.borrowed': 'Borrowed',
    'bookDetail.saved': 'Saved',
    'bookDetail.wishlist': 'Wishlist',
    'bookDetail.share': 'Share',
    'bookDetail.citation': 'Citation',
    'bookDetail.author': 'Author',
    'bookDetail.year': 'Year',
    'bookDetail.publisher': 'Publisher',
    'bookDetail.reviews': 'Reviews',
    'bookDetail.reserve': 'Reserve',
    'bookDetail.aiSubtitle': 'AI-powered analysis',
    'bookDetail.noAiSummary':
      'No AI summary is available for this publication.',
    'bookDetail.targetAudience': 'Suitable audience',
    'bookDetail.copyStatus': 'Copy status',
    'bookDetail.availableCount': 'Available',
    'bookDetail.borrowedCount': 'Borrowed',
    'bookDetail.notice': 'Notice',
    'bookDetail.totalCopiesNotice': '{total} copies ({available} available).',
    'bookDetail.allBorrowedNotice':
      'All copies are currently borrowed. Please reserve this title to keep your place.',
    'bookDetail.condition': 'Condition',
    'bookDetail.location': 'Location',
    'bookDetail.status': 'Status',
    'bookDetail.action': 'Action',
    'bookDetail.loadingCopies': 'Loading copy list...',
    'bookDetail.printedBook': 'Printed book',
    'bookDetail.borrowNow': 'Borrow now',
    'bookDetail.unavailable': 'Unavailable',
    'bookDetail.noCopies': 'No copies found',
    'bookDetail.showingCopies': 'Showing {from} - {to} of {total} copies',
    'bookDetail.overview': 'Overview',
    'bookDetail.toc': 'Table of contents',
    'bookDetail.related': 'Related books',
    'bookDetail.description': 'Detailed description',
    'bookDetail.noDescription': 'No description available.',
    'bookDetail.publicationInfo': 'Publication information',
    'bookDetail.callNumber': 'Call number (DDC)',
    'bookDetail.pages': 'Pages',
    'bookDetail.pageUnit': 'pages',
    'bookDetail.edition': 'Edition',
    'bookDetail.editionValue': '{edition} edition',
    'bookDetail.publicationYear': 'Publication year',
    'bookDetail.language': 'Language',
    'bookDetail.sizeWeight': 'Size / Weight',
    'bookDetail.tags': 'Tags',
    'bookDetail.noToc':
      'No table of contents is available for this publication.',
    'bookDetail.invalidToc': 'Invalid table of contents data.',
    'bookDetail.chapters': 'chapters',
    'bookDetail.noPageNumber': 'No page numbers',
    'bookDetail.pageShort': 'p.',
    'bookDetail.similarBooks': 'Similar books',
    'bookDetail.exploreMore': 'Explore more',
    'bookDetail.sameTopic': 'Books on the same topic',
    'bookDetail.viewAll': 'View all',
    'bookDetail.unknownAuthor': 'Unknown author',
    'bookDetail.availableCopiesShort': '{count} available',
    'bookDetail.noSimilar':
      'No similar books are available for this publication.',
    'bookDetail.dueExpected': 'Expected return',
    'bookDetail.reserveTitle': 'Reserve book',
    'bookDetail.reserveSubtitle': 'Choose your preferred pickup campus',
    'bookDetail.anyBranch': 'Any campus',
    'bookDetail.anyBranchSub':
      'Pick up at whichever campus returns a copy first',
    'bookDetail.noCopiesReserve':
      'This publication has no copies in the library yet. The system will notify you when a copy is available.',
    'bookDetail.availableAtBranch':
      'A copy is ready to borrow at this campus. You can visit the library directly without placing a reservation.',
    'bookDetail.processing': 'Processing...',
    'bookDetail.confirmReserve': 'Confirm reservation',
    'bookDetail.loginRequired':
      'Please log in with a student account to {action}.',
    'bookDetail.actionWishlist': 'save this book to your wishlist',
    'bookDetail.actionReserve': 'reserve this book',
    'bookDetail.actionBorrow': 'borrow this book',
    'bookDetail.removedWishlist': 'Removed from wishlist.',
    'bookDetail.addedWishlist': 'Added to wishlist!',
    'bookDetail.tryAgain': 'Something went wrong. Please try again.',
    'bookDetail.shareText': 'View "{title}" on Library74',
    'bookDetail.linkCopied': 'Book link copied.',
    'bookDetail.unknownPublisher': 'Unknown publisher',
    'bookDetail.citationCopied': 'Citation copied.',
    'bookDetail.reserveSuccess':
      'Reservation created successfully. We will notify you when the book is ready.',
    'bookDetail.reserveAvailableError':
      'This book is already available at the selected campus. You can borrow it directly at the library.',
    'bookDetail.reservePendingError':
      'You already have a pending reservation for this publication.',
    'bookDetail.reserveNoCopyError':
      'This branch currently has no copies of the book. Please choose another branch.',
    'bookDetail.reserveLimitError':
      'You have reached the maximum limit of 2 active reservations.',
    'bookDetail.reserveFineError':
      'You have unpaid fines. Please settle them before placing a reservation.',
    'bookDetail.reserveFailed': 'Unable to reserve this book right now.',
    'bookDetail.confirmBorrow': 'Are you sure you want to borrow this book?',
    'bookDetail.borrowFailed':
      'Unable to borrow this book right now. Please try again later.',
    'bookDetail.borrowSuccess': 'Borrow request created successfully!',
    'bookDetail.qrInstruction':
      'Please show this QR code to the librarian to pick up the book.',
    'bookDetail.transactionId': 'Transaction ID',
    'bookDetail.pickupDeadline': 'Pickup deadline',
    'bookDetail.status.available': 'Available',
    'bookDetail.status.reserved': 'Reserved',
    'bookDetail.status.borrowed': 'Borrowed',
    'bookDetail.status.maintenance': 'Under maintenance',
    'bookDetail.status.lost': 'Lost',
    'bookDetail.reviewBasedOn': 'Based on {count} reviews',
    'bookDetail.writeReview': 'Write your review',
    'bookDetail.yourRating': 'Your rating',
    'bookDetail.comment': 'Comment',
    'bookDetail.commentPlaceholder': 'Share your experience with this book...',
    'bookDetail.submitReview': 'Submit review',
    'bookDetail.communityReviews': 'Community reviews',
    'bookDetail.loadingReviews': 'Loading reviews...',
    'bookDetail.noReviews': 'No reviews yet for this publication.',
    'bookDetail.helpful': 'Helpful',
    'bookDetail.reply': 'Reply',
    'bookDetail.reviewRequired': 'Please enter your comment.',
    'bookDetail.reviewSuccess': 'Review submitted successfully!',
    'bookDetail.reviewFailed': 'Failed to submit review.',

    'home.aiPowered': 'Describe. Discover. Deliver.',
    'home.heroTitlePrefix': 'Find books with',
    'home.heroTitleHighlight': 'natural language',
    'home.heroDescription':
      'Discover academic materials with semantic search. You do not need exact keywords, just describe what you want to learn.',
    'home.searchPlaceholder':
      'Enter a title, author, ISBN, or describe the content you need...',
    'home.recentSearches': 'Recent:',
    'home.suggestions': 'Suggestions:',
    'home.viewNewest': 'View all new books',
    'home.exploreTopics': 'Explore by topic',
    'home.availableMaterials': 'Available materials',
    'home.activeStudents': 'Active students',
    'home.forYouEyebrow': 'Personalized',
    'home.forYouTitle': 'Recommended for you',
    'home.forYouSubtitle':
      'Personalized from your interests and borrowing history',
    'home.loginForRecommendations':
      'Log in to see personalized recommendations.',
    'home.emptyRecommendations':
      'Borrow or save books to receive better recommendations.',
    'home.categoriesEyebrow': 'Rich categories',
    'home.categoriesTitle': 'Explore by Topic',
    'home.categoriesSubtitle': 'Find academic materials by your field of study',
    'home.noCategories': 'No categories are available yet.',
    'home.allTopics': 'View all topics',
    'home.newBooks': 'New books',
    'home.newUpdated': 'Recently added',
    'home.loadingNewBooks': 'Loading new books...',
    'home.noNewBooks': 'No new books available.',
    'home.newTag': 'NEW',
    'home.popularBooks': 'Most borrowed',
    'home.trending': 'Trending',
    'home.loadingPopularBooks': 'Loading popular books...',
    'home.noPopularBooks': 'No popular books available.',
    'home.borrowCount': 'borrows',
    'home.aiTechnology': 'AI TECHNOLOGY',
    'home.aiHelpTitle': 'How does AI help you?',
    'home.aiHelpDesc':
      'Experience artificial intelligence for faster, more relevant academic search and discovery.',
    'home.contextTitle': 'Context-aware search',
    'home.contextDesc':
      'AI understands the intent behind your query instead of relying only on exact keyword matching, producing more relevant results than traditional search.',
    'home.behaviorTitle': 'Learns from behavior',
    'home.behaviorDesc':
      'The system learns from your borrowing history, saved books, and interactions so recommendations become more relevant over time.',
    'home.discoveryTitle': 'Smart discovery',
    'home.discoveryDesc':
      'AI connects related materials, suggests adjacent topics, and helps you discover useful sources you may not have considered.',
    'home.tryAiTitle': 'Experience AI-powered discovery today',
    'home.tryAiDesc':
      'Students use Library74 to study more effectively. Sign up for free and discover how AI can help you find knowledge faster.',
    'home.freeForStudents': '100% free for students',
    'home.unlimitedSearch': 'Unlimited searches',
    'home.support247': '24/7 support',
    'home.freeRegister': 'Sign up for free',
    'home.statsTitle': 'Key numbers',
    'home.statsSubtitle': 'Library74 serves the student community every day',
    'home.materials': 'Materials',
    'home.users': 'Users',
    'home.borrows': 'Borrows',
    'home.satisfaction': 'Satisfaction',
    'home.testimonialsEyebrow': 'USER TESTIMONIALS',
    'home.testimonialsTitle': 'What readers say about us',
    'home.testimonialsSubtitle': 'Authentic feedback from the user community',
    'home.reviewCountLabel': 'reviews',
    'home.satisfiedLabel': 'satisfied',
    'home.editSystemReview': 'Edit review',
    'home.reviewSystem': 'Review system',
    'home.submitSystemReview': 'Submit review',
    'home.viewAllReviews': 'View all reviews',
    'home.noSystemReviews': 'No system reviews yet.',
    'home.noSystemReviewsDesc':
      'Feedback appears here only after real users submit reviews.',
    'home.defaultReviewQuote': 'Rated {rating}/5 for the Library74 experience.',
    'home.reviewModalTitle': 'Review your experience',
    'home.reviewModalEditTitle': 'Edit system review',
    'home.reviewModalDesc':
      'Each account has one review and can update it anytime.',
    'home.reviewSatisfactionLevel': 'Satisfaction level',
    'home.reviewSatisfactionRule':
      'Reviews from 3 stars and above count as satisfied users in system statistics.',
    'home.reviewYourThoughts': 'Your thoughts',
    'home.reviewPlaceholder':
      'What made you satisfied, or what should Library74 improve?',
    'home.reviewWritingHint':
      'The best reviews are specific, concise, and authentic.',
    'home.reviewRequired': 'Please enter your system review.',
    'home.reviewSaveFailed': 'Could not save your review right now.',
    'home.readyTitle': 'Ready to begin?',
    'home.readyDesc':
      'Join students who use Library74 to improve their learning efficiency.',
    'home.exploreNow': 'Explore now',
    'home.noCredit':
      'No credit card required • Free forever for students • Start in 30 seconds',

    'categories.title': 'Book categories',
    'categories.subtitle':
      'Explore publications by the categories available in the library system',
    'categories.searchPlaceholder': 'Search categories...',
    'categories.unnamed': 'Unnamed category',
    'categories.parent': 'Parent group:',
    'categories.defaultDescription':
      'Browse materials classified under this category.',
    'categories.noMatch': 'No matching categories found.',
    'categories.realCategories': 'Actual categories',
    'categories.bookClassifications': 'Book classifications',
    'categories.onlineLookup': 'Online lookup',
  },
} as const;

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, fallback?: string) => string;
};

const LanguageContext = createContext<LanguageContextValue | undefined>(
  undefined
);

const normalizeLanguage = (value: string | null): Language =>
  value === 'en' ? 'en' : 'vi';

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  const [language, setLanguageState] = useState<Language>(() =>
    normalizeLanguage(localStorage.getItem(STORAGE_KEY))
  );

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language;
  }, [language]);

  const value = useMemo<LanguageContextValue>(
    () => ({
      language,
      setLanguage: setLanguageState,
      t: (key, fallback) => {
        const current = translations[language] as Record<string, string>;
        const base = translations.vi as Record<string, string>;
        return current[key] ?? base[key] ?? fallback ?? key;
      },
    }),
    [language]
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};

export const useTranslation = useLanguage;
