import { CopySummary, PublicationOverview } from '../../../api/circulationInquiryService';
import { useLanguage } from '../../../contexts/LanguageContext';
import { Badge, buttonClass, date, label, NewTabLink, Pager, useCopy } from './shared';

export default function BookOverview({ data, onPage, onCopy, onTransaction }: { data: PublicationOverview; onPage: (page: number) => void; onCopy: (item: CopySummary) => void; onTransaction: (id: string) => void }) {
  const t = useCopy(); const { language } = useLanguage(); const en = language === 'en'; const p = data.publication;
  return <div className="space-y-4"><div className="flex gap-4">{p.coverImageUrl && <img className="h-28 w-20 rounded-lg object-cover" src={p.coverImageUrl} alt="" />}<div><h3 className="text-lg font-bold">{p.publicationTitle}</h3><p className="mt-1 text-sm text-slate-600 dark:text-slate-300">{p.authors || t('Chưa có tác giả', 'Authors unavailable')}</p><div className="mt-3"><NewTabLink to={`/librarianpage/books/${p.publicationId}`}>{t('Mở chi tiết đầu sách', 'Open book details')}</NewTabLink></div></div></div>
    <dl className="grid grid-cols-2 gap-2 sm:grid-cols-4">{[
      [t('Tổng bản sao', 'Total copies'), data.counts.total], [t('Có sẵn, không chờ cất', 'Available, not awaiting shelving'), data.counts.ready], [t('Chờ cất kệ', 'Awaiting shelving'), data.counts.waiting], [t('Đang mượn', 'Borrowed'), data.counts.borrowed], [t('Giữ chờ nhận', 'Reserved'), data.counts.reserved], [t('Bảo trì', 'Maintenance'), data.counts.maintenance], [t('Mất', 'Lost'), data.counts.lost],
    ].map(([name, value]) => <div key={name} className="rounded-xl border border-slate-200 bg-slate-50 p-3 dark:border-slate-700 dark:bg-slate-800"><dt className="text-xs text-slate-600 dark:text-slate-300">{name}</dt><dd className="mt-1 text-lg font-bold">{value}</dd></div>)}</dl>
    <div className="overflow-x-auto rounded-xl border border-slate-200 dark:border-slate-700"><table className="w-full table-fixed break-words text-left text-sm"><thead className="bg-slate-50 dark:bg-slate-800"><tr>{[t('Barcode / Kệ', 'Barcode / Shelf'), t('Trạng thái', 'Status'), t('Người đang giữ / Hạn trả', 'Current borrower / Due'), t('Tra cứu', 'View')].map(name => <th scope="col" className="w-1/4 p-3 align-top" key={name}>{name}</th>)}</tr></thead><tbody>{data.copies.content.map(item => <tr key={item.itemId} className="border-t border-slate-100 dark:border-slate-700"><td className="p-3 align-top"><button className="font-mono font-semibold text-indigo-700 hover:underline dark:text-indigo-300" onClick={() => onCopy(item)}>{item.barcode}</button><div className="mt-1 text-xs">{item.branch || '—'}</div><strong className="mt-1 block text-blue-700 dark:text-blue-300">{item.location || t('Chưa có vị trí kệ', 'Shelf unassigned')}</strong></td><td className="p-3 align-top"><Badge value={item.status} />{item.waitingReshelving && item.status === 'AVAILABLE' && <p className="mt-2 text-xs text-amber-700 dark:text-amber-300">{t('Chờ cất kệ', 'Awaiting shelving')}</p>}<p className="mt-1 text-xs">{t('Tình trạng hiện tại', 'Current condition')}: {label(item.condition, en)}</p></td><td className="p-3 align-top">{item.holderName ? <><button className="text-left hover:underline" onClick={() => { if (item.transactionId) onTransaction(item.transactionId); }}>{item.holderName} · {item.holderStudentId}</button><p className="mt-1 text-xs">{date(item.dueDate, en)}</p></> : '—'}</td><td className="space-y-2 p-3 align-top"><button className={buttonClass} onClick={() => onCopy(item)}>{t('Vòng đời', 'Lifecycle')}</button><div><NewTabLink to={`/librarianpage/copies/${item.itemId}`}>{t('Chi tiết bản sao', 'Copy details')}</NewTabLink></div></td></tr>)}</tbody></table>{!data.copies.content.length && <p className="p-4 text-sm">{t('Không có bản sao tại cơ sở đã chọn.', 'No copies at the selected branch.')}</p>}<Pager data={data.copies} onPage={onPage} /></div>
  </div>;
}
